### ISSUE TITLE
failed subtest: 3

### ISSUE THREAD

**Issue by makorne** [tarantool/tradeparser#2] opened 2018-09-27 19:18 UTC
```
tarantool test.lua
TAP version 13
1..24
ok - date: 2017-03-30T00:00:00Z
ok - date: 2017-03-30T00:00:00Z
ok - date: 2017-03-05T16:52:53Z
ok - date: 2017-03-05T16:52:53Z
ok - date: 2017-03-05T00:00:00Z
not ok - date: 2017-03-04T21:00:00Z
  ---
  filename: test.lua
  trace:
  - line: 10
    source: '@test.lua'
    filename: test.lua
    what: Lua
    namewhat: local
    name: test_iso8601
    src: test.lua
  - line: 0
    source: '@test.lua'
    filename: test.lua
    what: main
    namewhat: 
    src: test.lua
  line: 0
  expected: 2017-03-04T21:00:00Z
  got: 2017-03-05T05:00:00Z
  ...
ok - xml: []
ok - xml: {"xml":"baz"}
ok - xml: []
ok - xml: {"xml":{"foo":"qux"}}
ok - xml: {"xml":[]}
ok - xml: {"xml":["frob1","frob2"]}
ok - xml: {"Cakes":[]}
ok - xml: {"xml":{"foo":1}}
not ok - xml: []
  ---
  filename: test.lua
  trace:
  - line: 16
    source: '@test.lua'
    filename: test.lua
    what: Lua
    namewhat: local
    name: test_xml
    src: test.lua
  - line: 0
    source: '@test.lua'
    filename: test.lua
    what: main
    namewhat: 
    src: test.lua
  line: 0
  expected: '[]'
  got: '{"xml":{"foo":0}}'
  ...
ok - xml: {"xml":{"foo":1.2345}}
ok - xml: {"xml":{"foo":0}}
ok - xml: {"xml":[true,true,false]}
ok - xml: {"xml":["A nice and long ASCII string",""]}
ok - xml: {"xml":{"foo":"Строка с UTF-8 символами"}}
not ok - xml: {"xml":[1488661200,1488672000,1488672000]}
  ---
  filename: test.lua
  trace:
  - line: 16
    source: '@test.lua'
    filename: test.lua
    what: Lua
    namewhat: local
    name: test_xml
    src: test.lua
  - line: 0
    source: '@test.lua'
    filename: test.lua
    what: main
    namewhat: 
    src: test.lua
  line: 0
  expected: '{"xml":[1488661200,1488672000,1488672000]}'
  got: '{"xml":[1488690000,1488672000,1488672000]}'
  ...
ok - xml: {"AssetFlow":{"FlowType":3,"Underlying":194382,"id":28652089}}
ok - xml: {"bar":"qux"}
ok - xml: null
# failed subtest: 3
```

```
tarantool -v
Tarantool 1.9.1-55-g1046f8516
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/lib/ccache/g++
C_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-1.9.1.55=. -specs=/usr/share/dpkg/no-pie-compile.specs -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -fno-gnu89-inline
CXX_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-1.9.1.55=. -specs=/usr/share/dpkg/no-pie-compile.specs -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof

```

**Comment by ghost** [comment] 2018-10-01 15:55
Unfortunately I can't reproduce this problem on my machine. Where do you run it?

Looks like date/time parsing functionality doesn't work as expected.

**Comment by filonenko-mikhail** [comment] 2022-01-19 07:11
Three years no info. Gently closing. Feel free to reopen.

**Closed as completed by filonenko-mikhail** 2022-01-19 07:11 UTC
